spring.application.name=DirectorySync

input.user.inputFileDirectory=C:/Tmp/3C/dirsync/delta/user/
input.user.processedFilePathDirectory=C:/Tmp/3C/dirsync/delta/user/processed

input.group.inputFileDirectory=C:/Tmp/3C/dirsync/delta/group/
input.group.processedFilePathDirectory=C:/Tmp/3C/dirsync/delta/group/processed

path.of.all.user.file.path=C:/Tmp/3C/dirsync/full/user/user2.ldif
path.of.all.group.file.path=C:/Tmp/3C/dirsync/full/group/group2.ldif

# LDAP configurations for an embedded server
ldap.userDN=cn=ldap_srv_acct_dir_sync,dc=cmmp-di-test,dc=ctg
ldap.password=CMMPctg@123
ldap.url=ldaps://159.138.152.30:9636/dc=cmmp-di-test,dc=ctg

cmmp.sync.source-bases[0]=ou=users,dc=example,dc=com
cmmp.sync.source-bases[1]=ou=contractors,dc=example,dc=com
cmmp.sync.source-bases[2]=ou=service-accounts,dc=example,dc=com

# If using an external server, replace with actual details:
# spring.security.ldap.urls=ldap://localhost:389/dc=example,dc=com
# spring.security.ldap.username=cn=admin,dc=example,dc=com
# spring.security.ldap.password=secret
