spring.application.name=DirectorySync

input.user.inputFileDirectory=C:/Tmp/3C/Coremail Log
input.user.processedFilePathDirectory=C:/Tmp/3C/Coremail Log

# LDAP configurations for an embedded server
ldap.userDN=cn=ldap_srv_acct_dir_sync,dc=cmmp-di-test,dc=ctg
ldap.password=CMMPctg@123
ldap.url=ldaps://159.138.152.30:9636/dc=cmmp-di-test,dc=ctg

# If using an external server, replace with actual details:
# spring.security.ldap.urls=ldap://localhost:389/dc=example,dc=com
# spring.security.ldap.username=cn=admin,dc=example,dc=com
# spring.security.ldap.password=secret
