spring.application.name=dirsync

# LDAP configurations for an embedded server
ldap.userDN=cn=user_ctg_simon_fung,DC=cmmp,DC=hksarg
ldap.password=P@ssw0rdCTG
ldap.url=ldap://94.74.110.140:9389

# If using an external server, replace with actual details:
# spring.security.ldap.urls=ldap://localhost:389/dc=example,dc=com
# spring.security.ldap.username=cn=admin,dc=example,dc=com
# spring.security.ldap.password=secret
